# Generated by Django 6.0.6 on 2026-06-22 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projetos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_projeto', models.CharField(max_length=255)),
                ('status_projeto', models.CharField(max_length=50)),
                ('valor_total_projeto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_entrada', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='ChatHistory',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='projeto',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='data_entrada',
        ),
        migrations.AddField(
            model_name='cliente',
            name='valor_total_cliente',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projetos',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='chat.cliente'),
        ),
        migrations.DeleteModel(
            name='Contrato',
        ),
        migrations.DeleteModel(
            name='Pagamento',
        ),
        migrations.DeleteModel(
            name='Projeto',
        ),
    ]
