# Generated by Django 6.0.6 on 2026-06-23 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_projetos_delete_chathistory_remove_pagamento_projeto_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projetos',
            new_name='Projeto',
        ),
    ]
