# Generated by Django 6.0.6 on 2026-06-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_projetos_projeto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='data_entrada',
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_entrada',
            field=models.DateField(blank=True, null=True),
        ),
    ]
