# Generated by Django 6.0.6 on 2026-06-23 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_projeto_data_entrada_cliente_data_entrada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='valor_total_cliente',
        ),
    ]
